'use client';
import {useEffect,useMemo,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';

type Stop={time:string,title:string,note:string,query?:string,baby?:string};
type Day={date:string,weekday:string,title:string,icon:string,summary:string,photo:string,route:string,distance:number,drive:number,toll:number,fuel:number,parking:number,stops:Stop[],rain:string};
const hotel='La manana Asahiyama Koendori 3-18 Minami 9-jo Nishi 15-chome Sapporo';
const days:Day[]=[
{date:'8/12',weekday:'三',title:'抵達北海道・札幌入住',icon:'✈️',summary:'第一天不趕景點，以入境、租車、採買、入住與休息為主。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/New%20Chitose%20Airport.jpg',route:'新千歲機場 → 札幌',distance:60,drive:75,toll:1430,fuel:800,parking:1000,stops:[
{time:'11:05',title:'IT234 抵達新千歲',note:'入境、領行李與整理寶寶用品，預留75–90分鐘。',query:'New Chitose Airport',baby:'先換尿布、餵奶，再前往租車櫃台。'},
{time:'12:40',title:'租車與安裝安全座椅',note:'確認ETC卡、保險、車損與滿油還車規定。',query:'New Chitose Airport Car Rental'},
{time:'13:30',title:'機場午餐',note:'不排熱門長隊店，讓寶寶先穩定休息。'},
{time:'14:30',title:'前往札幌',note:'約60–75分鐘；若寶寶哭鬧，於休息區短停。',query:hotel,baby:'安全座椅內連續乘坐盡量不超過約90分鐘。'},
{time:'16:00',title:'入住與附近採買',note:'購買飲用水、早餐、濕紙巾與簡單食物。',query:hotel},
{time:'18:00',title:'附近晚餐',note:'第一晚不進大通或狸小路，避免過度疲累。'}],rain:'不受影響；晚餐可改外帶回住宿。'},
{date:'8/13',weekday:'四',title:'小樽慢遊',icon:'⛵',summary:'小樽運河、堺町通、甜點與玻璃工藝，下午提早回札幌。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Otaru%20Canal.jpg',route:'札幌 → 小樽 → 札幌',distance:90,drive:130,toll:2460,fuel:1200,parking:1400,stops:[
{time:'08:30',title:'從住宿出發',note:'避開札幌尖峰，車程約55–70分鐘。',query:'Otaru Canal',baby:'出發前完成餵奶與換尿布。'},
{time:'09:45',title:'小樽運河',note:'散步與拍照約45分鐘，路面大致可推車。',query:'Otaru Canal'},
{time:'10:45',title:'堺町通散策',note:'北一硝子、音樂盒堂與沿途商店。',query:'Sakaimachi Street Otaru'},
{time:'12:00',title:'午餐',note:'挑可放推車、較寬敞的海鮮丼或壽司店。'},
{time:'13:30',title:'LeTAO甜點休息',note:'大人輪流休息與採買伴手禮。',query:'LeTAO Main Store Otaru',baby:'安排一次完整餵奶與換尿布。'},
{time:'15:00',title:'返回札幌',note:'傍晚不再追加遠距景點。',query:hotel}],rain:'保留音樂盒堂、北一硝子與LeTAO，縮短運河戶外散步。'},
{date:'8/14',weekday:'五',title:'美瑛・富良野花田',icon:'🌻',summary:'全程最長的一天，依青池、白鬚瀑布、四季彩之丘、富田農場順路安排。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Blue%20Pond%20in%20Biei%2C%20Hokkaido.jpg',route:'札幌 → 美瑛 → 富良野 → 札幌',distance:315,drive:350,toll:5720,fuel:4200,parking:1500,stops:[
{time:'06:30',title:'提早出發',note:'約80–90分鐘後安排第一次休息。',query:'Shirogane Blue Pond',baby:'出發前餵奶；途中固定停靠休息區。'},
{time:'09:30',title:'白金青池',note:'停留40–50分鐘，熱門時段人多。',query:'Shirogane Blue Pond'},
{time:'10:30',title:'白鬚瀑布',note:'橋上觀景約20–30分鐘。',query:'Shirahige Waterfall'},
{time:'11:45',title:'四季彩之丘',note:'午餐、花田與休息約90分鐘。',query:'Shikisai no Oka',baby:'此站安排餵奶、換尿布與完整休息。'},
{time:'14:00',title:'富田農場',note:'8月中改看其他花田、甜點與哈密瓜。',query:'Farm Tomita'},
{time:'16:00',title:'返回札幌',note:'回程至少安排一次休息與晚餐。',query:hotel}],rain:'改富良野起司工房、果醬園或旭川商場；青池視雨勢短停。'},
{date:'8/15',weekday:'六',title:'洞爺湖・湖上煙火',icon:'🎆',summary:'白天放慢步調，20:45看煙火；回札幌約23:15。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20Toya%20from%20Silo%20Observatory.jpg',route:'札幌 → 洞爺湖 → 札幌',distance:230,drive:300,toll:5160,fuel:3100,parking:1200,stops:[
{time:'10:00',title:'從札幌出發',note:'前一日長途後睡晚一點，途中休息一次。',query:'Lake Toya Onsen',baby:'白天補足睡眠，避免傍晚過度疲累。'},
{time:'12:30',title:'洞爺湖溫泉街午餐',note:'先找停車，再步行移動。',query:'Lake Toya Onsen'},
{time:'14:00',title:'湖畔散步與足湯',note:'平緩路段適合推車。',query:'Toyako Gurutto Chokoku Park'},
{time:'16:00',title:'咖啡廳或室內休息',note:'讓寶寶睡覺、喝奶。',baby:'煙火前完成餵奶、換尿布與加衣。'},
{time:'18:00',title:'提早晚餐',note:'避免煙火前才排隊。'},
{time:'20:15',title:'抵達湖畔觀賞區',note:'遠離人潮與音響中心。',query:'Toyako Onsen Fireworks Viewing'},
{time:'20:45',title:'洞爺湖長期煙火',note:'官方時段20:45–21:05；強風或天候不佳可能取消。'},
{time:'21:20',title:'返回札幌',note:'夜間駕駛約2小時，駕駛者勿飲酒。',query:hotel}],rain:'一般雨天可能照常施放，強風會取消；白天改火山科學館與咖啡廳。'},
{date:'8/16',weekday:'日',title:'旭山動物園',icon:'🐧',summary:'煙火翌日延後出發，以動物園為單一主景點。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Asahiyama%20Zoo.jpg',route:'札幌 → 旭川 → 札幌',distance:280,drive:300,toll:6920,fuel:3700,parking:500,stops:[
{time:'09:00',title:'從札幌出發',note:'可依寶寶狀態延後至09:30。',query:'Asahiyama Zoo'},
{time:'10:30',title:'高速休息區',note:'換尿布、伸展與短暫餵奶。'},
{time:'11:30',title:'旭山動物園',note:'先吃午餐，再看企鵝、海豹與北極熊。',query:'Asahiyama Zoo',baby:'園區有坡度；推車為主，背巾備用。'},
{time:'15:30',title:'離園',note:'精神好可到旭川商場吃早晚餐。'},
{time:'17:00',title:'返回札幌',note:'途中至少休息一次。',query:hotel}],rain:'動物館多可參觀；雨勢過大改旭川市科學館與AEON。'},
{date:'8/17',weekday:'一',title:'札幌市區慢遊',icon:'🏙️',summary:'白色戀人公園、北海道神宮、最後採買與整理行李。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Shiroi%20Koibito%20Park.jpg',route:'住宿 → 白色戀人 → 圓山 → 住宿',distance:45,drive:100,toll:0,fuel:600,parking:1800,stops:[
{time:'09:30',title:'白色戀人公園',note:'拍照、商店與室內設施約2小時。',query:'Shiroi Koibito Park'},
{time:'12:00',title:'午餐',note:'前往圓山一帶，避開狹小店面。'},
{time:'13:30',title:'北海道神宮與圓山公園',note:'遇高溫則縮短停留。',query:'Hokkaido Jingu'},
{time:'15:30',title:'回住宿整理行李',note:'確認護照、電子機票、還車地點與加油站。'},
{time:'17:30',title:'最後採買與晚餐',note:'以超市或狸小路為主。',query:'Tanukikoji Shopping Street'}],rain:'白色戀人公園室內區、札幌站百貨或AOAO SAPPORO。'},
{date:'8/18',weekday:'二',title:'回程日・新千歲機場',icon:'🧳',summary:'19:10起飛，建議15:45前完成還車、16:15抵達航廈。',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/New%20Chitose%20Airport.jpg',route:'札幌 → 新千歲機場',distance:65,drive:80,toll:1430,fuel:900,parking:0,stops:[
{time:'09:00',title:'最後整理',note:'檢查護照、奶粉、熱水、尿布與備用衣物。'},
{time:'10:30',title:'退房',note:'確認冰箱、插座、浴室與嬰兒用品。'},
{time:'11:00',title:'早午餐或近郊採買',note:'不安排與機場反方向的景點。'},
{time:'13:45',title:'離開札幌',note:'預留塞車、加油與接駁時間。',query:'New Chitose Airport Car Rental Return'},
{time:'15:00',title:'加滿油',note:'保留收據並確認油種。'},
{time:'15:30',title:'完成還車',note:'卸下全部行李再做車況確認。'},
{time:'16:15',title:'抵達國際航廈',note:'報到、托運、安檢與出境。',query:'New Chitose Airport International Terminal',baby:'先換尿布與餵奶，登機前再換一次。'},
{time:'19:10',title:'TR893 起飛',note:'目前班表22:35抵達桃園；以電子機票為準。'}],rain:'不受影響；取消戶外採買，提早前往機場。'}
];
const groups=[['證件與交通',['護照','Visit Japan Web','國際駕照正本','台灣駕照正本','租車確認單','旅遊保險','信用卡與日幣','ETC卡確認']],['寶寶餵養',['奶粉（多帶2天份）','奶瓶4支','奶瓶刷與清潔劑','消毒袋或消毒錠','熱水保溫瓶','冷水／常溫水瓶','圍兜與拍嗝巾','副食品與湯匙']],['寶寶外出',['尿布約60片','濕紙巾','屁屁膏','換尿布墊','推車','背巾','薄毯','遮陽帽','備用衣物2套','常備藥與體溫計']],['自駕與行李',['0歲適用安全座椅','手機架與充電線','行動電源','離線地圖','折疊購物袋','雨具','薄外套','舒適步行鞋']]] as const;
const nav=[['today','今天','⌂'],['trip','行程','◉'],['money','花費','¥'],['baby','寶寶','♡'],['list','清單','✓']];
const mapUrl=(q:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const yen=(n:number)=>new Intl.NumberFormat('zh-TW').format(n);
const dur=(m:number)=>`${Math.floor(m/60)}小時${m%60?`${m%60}分`:''}`;

export default function Home(){
 const[tab,setTab]=useState('today'),[idx,setIdx]=useState(0),[qr,setQr]=useState<string|null>(null),[expenses,setExpenses]=useState<Record<string,number>>({}),[baby,setBaby]=useState({milk:'',diaper:'',sleep:''}),[checked,setChecked]=useState<Record<string,boolean>>({});
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');try{setExpenses(JSON.parse(localStorage.getItem('trip-expenses')||'{}'));setBaby(JSON.parse(localStorage.getItem('trip-baby')||'{"milk":"","diaper":"","sleep":""}'));setChecked(JSON.parse(localStorage.getItem('trip-checklist')||'{}'))}catch{}},[]);
 const day=days[idx],fixed=day.toll+day.fuel+day.parking,total=Object.values(expenses).reduce((a,b)=>a+Number(b||0),0),count=Object.values(checked).filter(Boolean).length,items=groups.flatMap(g=>g[1]).length;
 const saveE=(v:Record<string,number>)=>{setExpenses(v);localStorage.setItem('trip-expenses',JSON.stringify(v))},saveB=(v:any)=>{setBaby(v);localStorage.setItem('trip-baby',JSON.stringify(v))},saveC=(v:Record<string,boolean>)=>{setChecked(v);localStorage.setItem('trip-checklist',JSON.stringify(v))};
 return <main className="safe-bottom mx-auto min-h-screen max-w-md px-4 pt-[calc(1rem+env(safe-area-inset-top))]">
  <header className="mb-5 flex items-center justify-between px-1"><div><p className="text-[11px] font-bold tracking-[.22em] text-[#2f7184]">北海道親子旅行</p><h1 className="mt-1 text-2xl font-black">2026・夏</h1></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#2f7184] text-xl text-white">🏔️</div></header>
  {tab==='today'&&<Today day={day} idx={idx} setIdx={setIdx} fixed={fixed} setQr={setQr} go={()=>setTab('trip')}/>} 
  {tab==='trip'&&<Trip day={day} idx={idx} setIdx={setIdx} setQr={setQr}/>} 
  {tab==='money'&&<Money day={day} idx={idx} setIdx={setIdx} expenses={expenses} save={saveE} total={total}/>} 
  {tab==='baby'&&<Baby baby={baby} save={saveB}/>} 
  {tab==='list'&&<Checklist checked={checked} save={saveC} count={count} items={items}/>} 
  <nav className="fixed inset-x-0 bottom-0 z-40 mx-auto max-w-md px-3 pb-[calc(.65rem+env(safe-area-inset-bottom))]"><div className="glass grid grid-cols-5 rounded-[1.55rem] p-2">{nav.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} className={`rounded-2xl py-2 ${tab===id?'bg-[#173642] text-white':'text-[#71858a]'}`}><span className="block text-lg">{icon}</span><span className="block text-[10px] font-bold">{label}</span></button>)}</div></nav>
  {qr&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#173642]/55 p-5 backdrop-blur-sm" onClick={()=>setQr(null)}><div className="w-full max-w-xs rounded-[2rem] bg-white p-6 text-center" onClick={e=>e.stopPropagation()}><h3 className="text-xl font-black">Google Maps導航</h3><p className="mt-1 text-xs text-[#6c7e82]">{qr}</p><div className="mx-auto mt-5 w-fit rounded-2xl bg-white p-3 shadow-inner"><QRCodeSVG value={mapUrl(qr)} size={190}/></div><a href={mapUrl(qr)} target="_blank" className="mt-5 block rounded-2xl bg-[#2f7184] px-4 py-3 font-black text-white">直接開啟導航</a><button onClick={()=>setQr(null)} className="mt-2 w-full py-3 text-sm font-bold">關閉</button></div></div>}
 </main>
}
function Today({day,idx,setIdx,fixed,setQr,go}:any){const first=day.stops.find((s:Stop)=>s.query);return <><section className="glass overflow-hidden rounded-[2rem]"><Photo src={day.photo} alt={day.title}/><div className="p-5"><p className="text-xs font-bold tracking-widest text-[#2f7184]">第{idx+1}天・{day.date}（{day.weekday}）</p><div className="mt-2 flex justify-between gap-3"><h2 className="text-3xl font-black leading-tight">{day.title}</h2><span className="text-4xl">{day.icon}</span></div><p className="mt-3 text-sm leading-6 text-[#6c7e82]">{day.summary}</p><div className="mt-5 grid grid-cols-3 gap-2"><Metric l="總里程" v={`${day.distance}公里`}/><Metric l="駕駛" v={dur(day.drive)}/><Metric l="交通估算" v={`${yen(fixed)}円`}/></div>{idx===3&&<div className="mt-4 rounded-2xl bg-[#173642] p-4 text-white"><p className="text-xs text-white/60">今晚重點</p><p className="mt-1 text-xl font-black">20:45–21:05 洞爺湖煙火</p></div>}<button onClick={go} className="mt-5 w-full rounded-2xl bg-[#2f7184] px-4 py-3.5 font-black text-white">查看完整行程</button>{first&&<button onClick={()=>setQr(first.query)} className="mt-2 w-full rounded-2xl bg-[#dceef1] px-4 py-3.5 font-black text-[#225b6b]">第一站導航 QR Code</button>}</div></section><section className="mt-7"><div className="mb-3 px-1"><p className="text-xs font-bold tracking-widest text-[#2f7184]">七天總覽</p><h2 className="text-2xl font-black">選擇日期</h2></div><div className="no-scrollbar -mx-4 flex gap-3 overflow-x-auto px-4 pb-2">{days.map((d,i)=><button key={d.date} onClick={()=>setIdx(i)} className={`min-w-[112px] rounded-[1.5rem] p-4 text-left ${i===idx?'bg-[#173642] text-white':'soft'}`}><p className="text-xs font-bold opacity-60">第{i+1}天</p><p className="mt-2 text-2xl">{d.icon}</p><p className="mt-2 text-sm font-black">{d.date}</p><p className="mt-1 text-[11px] leading-4 opacity-75">{d.title}</p></button>)}</div></section><section className="glass mt-6 rounded-[1.75rem] p-5"><p className="text-xs font-bold tracking-widest text-[#2f7184]">航班與住宿</p><Info t="去程 IT234" b="8/12　06:20 桃園 → 11:05 新千歲"/><Info t="回程 TR893" b="8/18　19:10 新千歲 → 22:35 桃園"/><Info t="住宿" b="札幌市中央區南9條西15丁目3-18"/><p className="mt-4 text-[11px] leading-5 text-[#829397]">航班可能調整，最終以電子機票與航空公司通知為準。</p></section></>}
function Trip({day,idx,setIdx,setQr}:any){return <><div className="no-scrollbar -mx-4 flex gap-2 overflow-x-auto px-4 pb-3">{days.map((d,i)=><button key={d.date} onClick={()=>setIdx(i)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${i===idx?'bg-[#173642] text-white':'bg-white/70'}`}>{d.date} {d.icon}</button>)}</div><section className="glass overflow-hidden rounded-[2rem]"><Photo src={day.photo} alt={day.title}/><div className="p-5"><p className="text-xs font-bold text-[#2f7184]">第{idx+1}天・{day.route}</p><h2 className="mt-2 text-2xl font-black">{day.title}</h2><p className="mt-2 text-sm leading-6 text-[#6c7e82]">{day.summary}</p></div></section><section className="mt-6 space-y-3">{day.stops.map((s:Stop)=><article key={s.time+s.title} className="soft rounded-[1.5rem] p-4"><div className="flex gap-3"><div className="grid h-9 min-w-16 place-items-center rounded-xl bg-[#dceef1] text-xs font-black text-[#2f7184]">{s.time}</div><div><h3 className="font-black">{s.title}</h3><p className="mt-1 text-sm leading-6 text-[#6c7e82]">{s.note}</p>{s.baby&&<p className="mt-2 rounded-xl bg-[#f5f3e9] px-3 py-2 text-xs leading-5">👶 {s.baby}</p>}{s.query&&<div className="mt-3 flex gap-2"><a href={mapUrl(s.query)} target="_blank" className="rounded-xl bg-[#2f7184] px-3 py-2 text-xs font-black text-white">開始導航</a><button onClick={()=>setQr(s.query!)} className="rounded-xl bg-[#e8eff0] px-3 py-2 text-xs font-black">QR Code</button></div>}</div></div></article>)}</section><section className="mt-6 rounded-[1.5rem] bg-[#f5f3e9] p-5"><p className="text-xs font-bold text-[#7d7457]">雨天備案</p><p className="mt-2 text-sm leading-6">{day.rain}</p></section><section className="glass mt-6 rounded-[1.5rem] p-5"><p className="text-xs font-bold text-[#2f7184]">每日交通估算</p><div className="mt-4 grid grid-cols-3 gap-2"><Metric l="油資" v={`${yen(day.fuel)}円`}/><Metric l="高速" v={`${yen(day.toll)}円`}/><Metric l="停車" v={`${yen(day.parking)}円`}/></div><p className="mt-3 text-[11px] leading-5 text-[#829397]">依一般汽油車與常見費用粗估，實際依車型、ETC與現場公告調整。</p></section></>}
function Money({day,idx,setIdx,expenses,save,total}:any){const keys=['餐費','購物','門票','寶寶用品','其他'];return <><section className="glass rounded-[2rem] p-5"><p className="text-xs font-bold text-[#2f7184]">旅費紀錄</p><h2 className="mt-2 text-3xl font-black">{yen(total)} 円</h2></section><div className="no-scrollbar -mx-4 mt-5 flex gap-2 overflow-x-auto px-4">{days.map((d,i)=><button key={d.date} onClick={()=>setIdx(i)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${i===idx?'bg-[#173642] text-white':'bg-white/70'}`}>{d.date}</button>)}</div><section className="soft mt-4 rounded-[1.75rem] p-5"><h3 className="text-xl font-black">{day.date}・{day.title}</h3><div className="mt-4 grid grid-cols-3 gap-2"><Metric l="油資" v={`${yen(day.fuel)}円`}/><Metric l="高速" v={`${yen(day.toll)}円`}/><Metric l="停車" v={`${yen(day.parking)}円`}/></div><div className="mt-5 space-y-3">{keys.map(k=>{const id=`${idx}-${k}`;return <label key={k} className="flex items-center gap-3 rounded-2xl bg-white/80 p-3"><span className="w-20 text-sm font-bold">{k}</span><input inputMode="numeric" value={expenses[id]||''} onChange={e=>save({...expenses,[id]:Number(e.target.value)})} placeholder="0" className="min-w-0 flex-1 bg-transparent text-right text-lg font-black outline-none"/><span>円</span></label>})}</div></section></>}
function Baby({baby,save}:any){return <><section className="glass rounded-[2rem] p-5"><p className="text-xs font-bold text-[#2f7184]">寶寶旅行紀錄</p><h2 className="mt-2 text-3xl font-black">簡單記下時間</h2><p className="mt-2 text-sm text-[#6c7e82]">資料只留在目前手機瀏覽器。</p></section>{[['milk','🍼','上次喝奶'],['diaper','🧷','上次換尿布'],['sleep','💤','上次睡醒']].map(([k,i,t])=><label key={k} className="soft mt-3 flex items-center gap-4 rounded-[1.5rem] p-4"><span className="text-3xl">{i}</span><div className="flex-1"><p className="text-sm font-bold text-[#6c7e82]">{t}</p><input value={baby[k]} onChange={e=>save({...baby,[k]:e.target.value})} placeholder="例如 14:30" className="mt-1 w-full bg-transparent text-xl font-black outline-none"/></div></label>)}<section className="mt-6 rounded-[1.5rem] bg-[#f5f3e9] p-5"><h3 className="font-black">自駕照護原則</h3><p className="mt-2 text-sm leading-6">每約60–90分鐘依狀態休息。車輛行進中不可抱離安全座椅餵奶；需要安撫時先停到安全地點。</p></section></>}
function Checklist({checked,save,count,items}:any){return <><section className="glass rounded-[2rem] p-5"><p className="text-xs font-bold text-[#2f7184]">行前檢查</p><h2 className="mt-2 text-3xl font-black">{count} / {items}</h2><div className="mt-4 h-2 rounded-full bg-[#dce5e4]"><div className="h-full rounded-full bg-[#2f7184]" style={{width:`${count/items*100}%`}}/></div></section><section className="mt-5 space-y-4">{groups.map(([title,arr])=><div key={title} className="soft rounded-[1.5rem] p-5"><h3 className="text-lg font-black">{title}</h3><div className="mt-3 space-y-2">{arr.map(item=><label key={item} className="flex items-center gap-3 py-1.5"><input type="checkbox" checked={!!checked[item]} onChange={e=>save({...checked,[item]:e.target.checked})}/><span className={`text-sm ${checked[item]?'line-through opacity-45':''}`}>{item}</span></label>)}</div></div>)}</section><section className="glass mt-5 rounded-[1.5rem] p-5"><h3 className="font-black">加入 iPhone 主畫面</h3><p className="mt-2 text-sm leading-6 text-[#6c7e82]">Safari開啟網站 → 分享 → 加入主畫面，即可像App使用。</p></section></>}
function Photo({src,alt}:{src:string,alt:string}){const[bad,setBad]=useState(false);return <div className="photo-fallback relative h-52 overflow-hidden">{!bad&&<img src={src} alt={alt} onError={()=>setBad(true)} className="h-full w-full object-cover"/>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/45 to-transparent px-4 pb-3 pt-10 text-xs font-bold text-white">{alt}</div></div>}
function Metric({l,v}:{l:string,v:string}){return <div className="rounded-2xl bg-[#edf3f2] p-3"><p className="text-[10px] font-bold text-[#829397]">{l}</p><p className="mt-1 text-xs font-black">{v}</p></div>}
function Info({t,b}:{t:string,b:string}){return <div className="mt-3 rounded-2xl bg-white/75 p-3"><p className="text-sm font-black">{t}</p><p className="mt-1 text-xs text-[#6c7e82]">{b}</p></div>}
